spring.application.name=Price-Comparison

spring.datasource.url=jdbc:mysql://localhost:3306/price-comparison?useSSL=false
spring.datasource.username=root
spring.datasource.password=IsEvFadr2!
spring.jpa.hibernate.ddl-auto=update